additionalProperties:
  npmName: '@cloudinary/media-delivery-api'
  npmVersion: '0.1.2-beta'
  httpUserAgent: CloudinaryMENodeJS
files:
  LICENSE.md: {}
  README.md: {}
  api_doc.mustache:
    destinationFilename: .md
    templateType: APIDocs
  readme.mustache:
    destinationFilename: README.md
    templateType: SupportingFiles

