additionalProperties:
  developerOrganization: Cloudinary
  gitUserId: cloudinary
  infoUrl: https://cloudinary.com
  httpUserAgent: CloudinaryPHP
  apiPackage: Api
  invokerPackage: Cloudinary\MediaDelivery
files:
  LICENSE.mustache:
    templateType: SupportingFiles
    destinationFilename: LICENSE
