additionalProperties:
  developerOrganization: Cloudinary
  gitUserId: cloudinary
  infoUrl: https://cloudinary.com
  apiPackage: Api
  invokerPackage: Cloudinary\MediaDelivery
  httpUserAgent: CloudinaryMEPHP
  artifactVersion: 0.1.2-beta
files:
  LICENSE.mustache:
    templateType: SupportingFiles
    destinationFilename: LICENSE
