additionalProperties:
  developerOrganization: Cloudinary
  gitUserId: cloudinary
  infoUrl: https://cloudinary.com
  apiPackage: Api
  invokerPackage: Cloudinary\MediaDelivery
  httpUserAgent: CloudinaryMEPHP
files:
  LICENSE.mustache:
    templateType: SupportingFiles
    destinationFilename: LICENSE
